# -*- coding: utf-8 -*-

# list of random replies

replies_dict = {
    'kommunist': ['Verdammte Kommunisten',
                  'Wer hat uns verraten?',
                  'Das ist nun doch zu einfach!',
                  'das konzept ist eigentlich gut, nur die Umsetzungen...',
                  'ein gesellschaftsentwurf wie in schlumpfhausen...',
                  'In der freien Welt gibt es sowas nicht...'],
    'ak-47': ['Kommunisten-Waffe',
              u'zuverlässige Waffe!',
              'Terroristen-Eisen',
              'Jonger, mit selbstreinigender Kammer'],
    'usa': [u'bestes Land überhaupt',
              u'USA? die spionieren uns aus!',
              u'Germantown, Miller Light, Jonger, grenzenlose Freiheit'],
    'kalaschnikow': ['Kommunisten-Waffe',
                     u'zuverlässige Waffe!',
                     'Terroristen-Eisen',
                     'Gebaut, um den Faschismus zu bekämpfen, und jetzt hat sogar Osama Bin Laden eine'],
    'schorle': ['einer geht noch',
                'mit 3 Eis!',
                'ich trink den lieber pur',
                'Schorle Null Vier'],
    'gesellschaft': ['gesellschaft ist eh kaputt',
                     'meine Steuern!',
                     'nur noch Sozialpädagogen und Weicheier'],
    'teilen': ['wer teilt verliert',
               'jeder sollte was abgeben, wenn er genug hat',
               'und was kommt dann? Der Kommunismus?'],
    'waffe': ['mehr davon',
              'jeder sollte eine haben',
              'sind zurecht verboten',
              'Warum ist Europa auf der Karte Dunkel? - Keine Waffen'],
    'nra': ['eine wichtige, gesellschaftsbildende Institution',
            'ziemlich konservativer laden'],
    'kollege': ['die besten. also deine.',
                'manchmal sind sie schon komisch',
                'Kollegen? Kameraden!'],
    'firma': ['gibt nur eine',
              '@aexea',
              u'klagt nicht, kämpft'],
    'suite': ['Prost!',
              'schon wieder?'],
    '212': ['Prost!',
            'schon wieder?'],
    'minibar': ['Prost!',
                'schon wieder?'],
    'schnitzel': ['urdeutsches gericht',
                  'gibts das heute mal in vegetarisch?'],
    'damals': ['damals... als startup!',
               'damals war eh alles besser',
               'naja, heute ist es eigentlich schon cool.',
               'ein Scall, Jonger. Ein Scall!'],
    'krieg': ['eigentlich haben wir den gar nicht so verloren',
              u'läuft!'],
    'freund': ['freunde sollte man haben'],
    'nerd': ['davon haben wir echt einige mittlerweile',
             'coole jungs',
             'die Moons!'
             'rennen rum und nennen sich Gummibären, Smarties, Ghostbuster oder verdammte Schreiner'],
    'bier': ['noch nen schorle dazu?',
             'lieber nen schorle',
             'irgendwo ist immer nach 4'],
    'clinton': ['one miller lite please!'],
    'beer': ['one miller lite please!'],
    'vfb': ['hoffentlich steigen wir dann bald wieder auf',
            u'müsste man mal abwickeln und neumachen'],
    'neulich': ['neulich war nach damals'],
    'spassfest': ['mit parade truck!',
                  u'nen original oktoberfestbesuche müsste man auch wieder mal machen'],
    'germantown': ['mit parade truck!',
                   u'nen original oktoberfestbesuche müsste man auch wieder mal machen'],
    'schankstelle': ['vollmachen',
                   u'ist weibsvolk anwensend?'],
}

nothing_found = ['ich weis gar nicht, was ich dazu sagen soll.',
                 u'mir gehen die texte aus',
                 u'unfassbar',
                 u'ich bin sprachlos',
                 u'Jo!',
                 u'Yo!',
                 u'Prost?',
                 u'Alter!',
                 u'Jonger!',
                 ]
